### ISSUE TITLE
Create shared components

### ISSUE THREAD

**Issue by VitalikMatvieiev** [VitalikMatvieiev/edu-platform#22]

**Comment by VitalikMatvieiev** [comment]
@Virsta @iverbitskyi @Vlad-2109 @tanyaivattt

**Comment by Vlad-2109** [comment]
![Image](https://github.com/VitalikMatvieiev/edu-platform/assets/127695738/dc2e85f1-5ce5-458c-b51f-d5ecda48abd7)



![Image](https://github.com/VitalikMatvieiev/edu-platform/assets/127695738/48879fea-28f1-45de-b124-09633f01fe45)

button for submit in login and registration pages
--------------------------------------------------------------------
styles(src/components/button/_button.scss):

@import url("https://fonts.googleapis.com/css2?family=Lexend:wght@500&display=swap");

$font-lexend: "Lexend", sans-serif;

@mixin lexend-medium {
  font-family: $font-lexend;
  font-weight: 500;
}

.btn-submit {
  width: 376px;
  height: 56px;
  padding: 16px 0 16px 0;
  background-color: #7101ff;
  @include lexend-medium;
  font-size: 16px;
  line-height: 24px;
  letter-spacing: -0.32px;
  color: #fff;
  text-align: center;
  border: none;
  &:hover {
    background-color: lighten(#7101ff, 15%);
    cursor: pointer;
  }
}

**Comment by Virsta** [comment]
![Image](https://github.com/VitalikMatvieiev/edu-platform/assets/38349965/ff18348c-ab2e-435e-b9e3-28e5483bec61)

This input

**Comment by Virsta** [comment]
![Image](https://github.com/VitalikMatvieiev/edu-platform/assets/38349965/87aff1b3-5416-4f04-a6f9-03d6149f0dac)

sidebar will use on every page, when user sign in

**Comment by Virsta** [comment]
![Image](https://github.com/VitalikMatvieiev/edu-platform/assets/38349965/37003b17-1a76-489a-b647-cd82d8900462)

button with opportunities change background and content
